deployment:
  replicaCount: 1
  image:
    tag: ""
    registry: ""
    name: ner-server
    imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
      nvidia.com/gpu: 1
    limits:
      cpu: 500m
      memory: 3.8Gi
      nvidia.com/gpu: 1

modelPaths:
  - arch: huggingface
    lang: he
    path: gs://sefaria-ml-models/he_ref_model_berel.tar.gz
    type: named_entity
  - arch: spacy
    lang: en
    path: gs://sefaria-ml-models/en_ner_model.tar.gz
    type: named_entity
  - arch: spacy
    lang: he
    path: gs://sefaria-ml-models/subref_model.tar.gz
    type: ref_part
  - arch: spacy
    lang: en
    path: gs://sefaria-ml-models/en_subref_model.tar.gz
    type: ref_part

serviceAccount:
  create: true
  # name:
  annotations: {}
